baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'antif4.com'

[menus]
  [[menus.main]]
    name = 'FAQ'
    pageRef = '/faq'
    weight = 20

  [[menus.main]]
    name = 'About'
    pageRef = '/about-us'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
